-- MySQL Script generated by MySQL Workbench
-- vie 29 abr 2022 16:35:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema empresa_transporte
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema empresa_transporte
-- -----------------------------------------------------
USE `sllamosas806` ;

-- -----------------------------------------------------
-- Table `sllamosas806`.`EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`EMPRESA` (
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`CIUDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`CIUDAD` (
  `nombreCiudad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombreCiudad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`DELEGACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`DELEGACION` (
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` INT NULL,
  `ciudad` VARCHAR(45) NULL,
  `fk_EmpresaNombre` VARCHAR(45) NOT NULL,
  `fk_CiudadNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `fk_DELEGACION_EMPRESA_idx` (`fk_EmpresaNombre` ASC) VISIBLE,
  INDEX `fk_DELEGACION_CIUDAD1_idx` (`fk_CiudadNombre` ASC) VISIBLE,
  CONSTRAINT `fk_DELEGACION_EMPRESA`
    FOREIGN KEY (`fk_EmpresaNombre`)
    REFERENCES `sllamosas806`.`EMPRESA` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DELEGACION_CIUDAD1`
    FOREIGN KEY (`fk_CiudadNombre`)
    REFERENCES `sllamosas806`.`CIUDAD` (`nombreCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`CAMION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`CAMION` (
  `matricula` INT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `tara` VARCHAR(45) NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`VIAJE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`VIAJE` (
  `idVIAJE` INT NOT NULL,
  `fk_DelegacionNombre` VARCHAR(45) NOT NULL,
  `fk_CamionMatricula` INT NOT NULL,
  PRIMARY KEY (`idVIAJE`, `fk_DelegacionNombre`),
  INDEX `fk_VIAJE_DELEGACION1_idx` (`fk_DelegacionNombre` ASC) VISIBLE,
  INDEX `fk_VIAJE_CAMION1_idx` (`fk_CamionMatricula` ASC) VISIBLE,
  CONSTRAINT `fk_VIAJE_DELEGACION1`
    FOREIGN KEY (`fk_DelegacionNombre`)
    REFERENCES `sllamosas806`.`DELEGACION` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VIAJE_CAMION1`
    FOREIGN KEY (`fk_CamionMatricula`)
    REFERENCES `sllamosas806`.`CAMION` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`FECHA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`FECHA` (
  `fecha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`EMPLEADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`EMPLEADO` (
  `idPersonal` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `anioNacimiento` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersonal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`ADMINISTATIVO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`ADMINISTATIVO` (
  `nivelEstudios` VARCHAR(45) NULL,
  `fk_EmpeladoIdPersonal` INT NOT NULL,
  PRIMARY KEY (`fk_EmpeladoIdPersonal`),
  CONSTRAINT `fk_ADMINISTATIVO_EMPLEADO1`
    FOREIGN KEY (`fk_EmpeladoIdPersonal`)
    REFERENCES `sllamosas806`.`EMPLEADO` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`CONDUCTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`CONDUCTOR` (
  `anioCarnet` INT NULL,
  `tipoCarnet` VARCHAR(45) NULL,
  `fk_EmpleadoIdPersonal` INT NOT NULL,
  PRIMARY KEY (`fk_EmpleadoIdPersonal`),
  CONSTRAINT `fk_CONDUCTOR_EMPLEADO1`
    FOREIGN KEY (`fk_EmpleadoIdPersonal`)
    REFERENCES `sllamosas806`.`EMPLEADO` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`ASIGNACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`ASIGNACION` (
  `fk_EmpleadoIdPersonal` INT NOT NULL,
  `fk_Fecha` VARCHAR(45) NOT NULL,
  `fk_DelegacionNombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fk_EmpleadoIdPersonal`, `fk_Fecha`),
  INDEX `fk_EMPLEADO_has_FECHA_FECHA1_idx` (`fk_Fecha` ASC) VISIBLE,
  INDEX `fk_EMPLEADO_has_FECHA_EMPLEADO1_idx` (`fk_EmpleadoIdPersonal` ASC) VISIBLE,
  INDEX `fk_ASIGNACION_DELEGACION1_idx` (`fk_DelegacionNombre` ASC) VISIBLE,
  CONSTRAINT `fk_EMPLEADO_has_FECHA_EMPLEADO1`
    FOREIGN KEY (`fk_EmpleadoIdPersonal`)
    REFERENCES `sllamosas806`.`EMPLEADO` (`idPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLEADO_has_FECHA_FECHA1`
    FOREIGN KEY (`fk_Fecha`)
    REFERENCES `sllamosas806`.`FECHA` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ASIGNACION_DELEGACION1`
    FOREIGN KEY (`fk_DelegacionNombre`)
    REFERENCES `sllamosas806`.`DELEGACION` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`RECORRIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`RECORRIDO` (
  `fk_CiudadNombre` VARCHAR(45) NOT NULL,
  `fk_ViajeId` INT NOT NULL,
  `fk_NombreDelegacion` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NULL,
  `hora` VARCHAR(45) NULL,
  PRIMARY KEY (`fk_CiudadNombre`, `fk_ViajeId`, `fk_NombreDelegacion`),
  INDEX `fk_CIUDAD_has_VIAJE_VIAJE1_idx` (`fk_ViajeId` ASC, `fk_NombreDelegacion` ASC) VISIBLE,
  INDEX `fk_CIUDAD_has_VIAJE_CIUDAD1_idx` (`fk_CiudadNombre` ASC) VISIBLE,
  CONSTRAINT `fk_CIUDAD_has_VIAJE_CIUDAD1`
    FOREIGN KEY (`fk_CiudadNombre`)
    REFERENCES `sllamosas806`.`CIUDAD` (`nombreCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CIUDAD_has_VIAJE_VIAJE1`
    FOREIGN KEY (`fk_ViajeId` , `fk_NombreDelegacion`)
    REFERENCES `sllamosas806`.`VIAJE` (`idVIAJE` , `fk_DelegacionNombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`ENTREGA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`ENTREGA` (
  `fk_CiudadNombre` VARCHAR(45) NOT NULL,
  `fk_ViajeId` INT NOT NULL,
  `fk_ViajeDelegacion` VARCHAR(45) NOT NULL,
  `fk_idCLIENTE` INT NOT NULL,
  `paquetesDescargados` INT NULL,
  `paquetesCargados` VARCHAR(45) NULL,
  PRIMARY KEY (`fk_CiudadNombre`, `fk_ViajeId`, `fk_ViajeDelegacion`, `fk_idCLIENTE`),
  INDEX `fk_RECORRIDO_has_CLIENTE_CLIENTE1_idx` (`fk_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_RECORRIDO_has_CLIENTE_RECORRIDO1_idx` (`fk_CiudadNombre` ASC, `fk_ViajeId` ASC, `fk_ViajeDelegacion` ASC) VISIBLE,
  CONSTRAINT `fk_RECORRIDO_has_CLIENTE_RECORRIDO1`
    FOREIGN KEY (`fk_CiudadNombre` , `fk_ViajeId` , `fk_ViajeDelegacion`)
    REFERENCES `sllamosas806`.`RECORRIDO` (`fk_CiudadNombre` , `fk_ViajeId` , `fk_NombreDelegacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RECORRIDO_has_CLIENTE_CLIENTE1`
    FOREIGN KEY (`fk_idCLIENTE`)
    REFERENCES `sllamosas806`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sllamosas806`.`DESIGNACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sllamosas806`.`DESIGNACION` (
  `CONDUCTOR_fk_EmpleadoIdPersonal` INT NOT NULL,
  `VIAJE_idVIAJE` INT NOT NULL,
  `VIAJE_fk_DelegacionNombre` VARCHAR(45) NOT NULL,
  `dietaImporte` VARCHAR(45) NULL,
  PRIMARY KEY (`CONDUCTOR_fk_EmpleadoIdPersonal`, `VIAJE_idVIAJE`, `VIAJE_fk_DelegacionNombre`),
  INDEX `fk_CONDUCTOR_has_VIAJE_VIAJE1_idx` (`VIAJE_idVIAJE` ASC, `VIAJE_fk_DelegacionNombre` ASC) VISIBLE,
  INDEX `fk_CONDUCTOR_has_VIAJE_CONDUCTOR1_idx` (`CONDUCTOR_fk_EmpleadoIdPersonal` ASC) VISIBLE,
  CONSTRAINT `fk_CONDUCTOR_has_VIAJE_CONDUCTOR1`
    FOREIGN KEY (`CONDUCTOR_fk_EmpleadoIdPersonal`)
    REFERENCES `sllamosas806`.`CONDUCTOR` (`fk_EmpleadoIdPersonal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONDUCTOR_has_VIAJE_VIAJE1`
    FOREIGN KEY (`VIAJE_idVIAJE` , `VIAJE_fk_DelegacionNombre`)
    REFERENCES `sllamosas806`.`VIAJE` (`idVIAJE` , `fk_DelegacionNombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
