-- MySQL Script generated by MySQL Workbench
-- jue 16 jun 2022 15:37:17
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Final` ;
USE `Final` ;

-- -----------------------------------------------------
-- Table `Final`.`Semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Final`.`Semestre` (
  `idSemestre` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idSemestre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Final`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Final`.`Materia` (
  `idMateria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `cargaHoraria` VARCHAR(45) NULL,
  `cantidadAlumnos` VARCHAR(45) NULL,
  `idCorrelativa` INT NULL,
  `idCorrelativa2` INT NULL,
  `idSemestre` INT NOT NULL,
  PRIMARY KEY (`idMateria`),
  INDEX `fk_Materia_Materia_idx` (`idCorrelativa` ASC) VISIBLE,
  INDEX `fk_Materia_Departamento1_idx` (`idSemestre` ASC) VISIBLE,
  CONSTRAINT `fk_Materia_Materia`
    FOREIGN KEY (`idCorrelativa`)
    REFERENCES `Final`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_Departamento1`
    FOREIGN KEY (`idSemestre`)
    REFERENCES `Final`.`Semestre` (`idSemestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = armscii8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
